### ISSUE TITLE
Unmanaged descriptor

### ISSUE THREAD

**Issue by Farhad7d7** [pengrad/android-maps-async-markers#1]
the icon loads awesome when map starts, but when i scroll along map, it cause a FATAL EXCEPTION:

java.lang.IllegalArgumentException: Unmanaged descriptor

> at com.google.maps.api.android.lib6.common.l.b(:com.google.android.gms.DynamiteModulesB:20)
>                                                                            at com.google.maps.api.android.lib6.impl.m.c(:com.google.android.gms.DynamiteModulesB:17)
>                                                                            at com.google.maps.api.android.lib6.impl.cy.a(:com.google.android.gms.DynamiteModulesB:179)
>                                                                            at com.google.android.gms.maps.model.internal.q.onTransact(:com.google.android.gms.DynamiteModulesB:88)
> at android.os.Binder.transact(Binder.java:310)
>                                                                            at com.google.android.gms.internal.zzed.zzb(Unknown Source)
>                                                                            at com.google.android.gms.maps.model.internal.zzr.zzK(Unknown Source)
>                                                                            at com.google.android.gms.maps.model.Marker.setIcon(Unknown Source)
>                                                                            at com.negarine.darbasti.view.MainActivity$8.onResourceReady(MainActivity.java:630)
>                                                                            at com.negarine.darbasti.view.MainActivity$8.onResourceReady(MainActivity.java:626)
>                                                                            at com.bumptech.glide.request.GenericRequest.onResourceReady(GenericRequest.java:525)
>                                                                            at com.bumptech.glide.request.GenericRequest.onResourceReady(GenericRequest.java:507)
>                                                                            at com.bumptech.glide.load.engine.EngineJob.handleResultOnMainThread(EngineJob.java:158)
>                                                                            at com.bumptech.glide.load.engine.EngineJob.access$100(EngineJob.java:22)
>                                                                            at com.bumptech.glide.load.engine.EngineJob$MainThreadCallback.handleMessage(EngineJob.java:202)
>                                                                            at android.os.Handler.dispatchMessage(Handler.java:103)
>                                                                            at android.os.Looper.loop(Looper.java:194)
>                                                                            at android.app.ActivityThread.main(ActivityThread.java:5433)
>                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
>                                                                            at java.lang.reflect.Method.invoke(Method.java:525)
>                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:924)
>                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:691)
>                                                                            at dalvik.system.NativeStart.main(Native Method)

**Here is My Code:**

 ```
private void loadMarkerIcon(final Marker marker1, CarsModel car) {
        Glide.with(this).load(car.getCarIcon()).asBitmap().fitCenter().skipMemoryCache(true).into(new SimpleTarget<Bitmap>() {
            @Override
            public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> glideAnimation) {
                BitmapDescriptor icon = BitmapDescriptorFactory.fromBitmap(resource);
                marker1.setIcon(icon);
            }
        });
    }
```
What's the main cause of this issue? and also What should i do?
Thanks a lot for response.

**Comment by haris15** [comment]
do you find solution ?
